blog/urls.py
from django.conf.urls import patterns, url

from blog import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^read/(?P<post_id>\d+)/$', views.detail, name='detail'),
#    url(r'^comments/', include('django.contrib.comments.urls')),
)

mudkips/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mudkips.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/', include('blog.urls', namespace='blog')),
)

blog/models.py
from django.db import models
from django.contrib.auth.models import User

class Category(models.Model):
    cat_name = models.CharField(max_length=50)

    class Meta:
        verbose_name_plural = "Categories"
    def __unicode__(self):
        return self.cat_name

class Post(models.Model):
    post_title = models.CharField(max_length=100)
    post_body = models.TextField()
    post_category = models.ManyToManyField(Category)
    post_date = models.DateTimeField(auto_now=True)
    post_author = models.ForeignKey(User)
    post_published = models.BooleanField()
    
    def is_published(self):
        return self.post_published
    
    def __unicode__(self):
        return self.post_title
        
#class Comment(models.Model):
#    comment_title = models.CharField(max_length=100)
#    comment_body = models.TextField()
#    comment_date = models.DateTimeField(auto_now=True)
#    comment_author = models.ForeignKey(User)
#    comment_moderating = models.BooleanField()
#    comment_post = models.ForeignKey(Post)
#    def __unicode__(self):
#        return self.comment_title
    
class Settings(models.Model):
    setting_commentmod = models.BooleanField()
    
class Nav(models.Model):
    nav_title = models.CharField(max_length=50)
    nav_url = models.CharField(max_length=200)
    nav_dropdown = models.ForeignKey('self', blank=True, null=True)
    def __unicode__(self):
        return self.nav_title
    
    

    
    
    

blog/views.py
from django.http import HttpResponse
from django.template import RequestContext, loader
from django.shortcuts import render, get_object_or_404, render_to_response
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from blog.models import Post, Nav

def index(request):
    #template = loader.get_template('blog/index.html')
    posts = Post.objects.all()
    paginator = Paginator(posts, 4)
    page = request.GET.get('page')
    try:
        pages = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        pages = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        pages = paginator.page(paginator.num_pages)



    context = RequestContext(request, {
            'paginator': paginator,
            'posts' : posts,
            'pages' : pages,
            'btitle' : "Luz's Blog",
            'blink' : "/blog",
            'Nav' : Nav.objects.all(),
    })
    return render_to_response('blog/index.html', context )
    
def detail(request, post_id):
    template = loader.get_template('blog/post.html')
    try:
        post = Post.objects.get(pk=post_id)
        
    except Post.DoesNotExist:
        raise Http404

#    comments = post.comment_set.all()
    context = RequestContext(request, {
            'post': post,
            'btitle' : "Luz's Blog",
            'blink' : "/blog",
            'Nav' : Nav.objects.all(),
    })
    return HttpResponse(template.render(context))
    

blog/templates/blog/head.html
{% load staticfiles %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="{% static "blog/favicon.ico" %}">

    <title>{{ btitle }}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static "blog/dist/css/bootstrap.css" %}" rel="stylesheet">
    <link href="{% static "blog/dist/css/bootstrap-theme.css" %}" rel="stylesheet">
    <link href="{% static "blog/custom.css" %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <!-- link href="sticky-footer-navbar.css" rel="stylesheet"-->

    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="../../docs-assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <!-- Wrap all page content here -->
    <div id="wrap">
      <!-- Fixed navbar -->
      <div class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ blink }}">{{ btitle }}</a>
            </div>
          <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
            {% if Nav %}
                {% for link in Nav %}
                    {% if link.nav_set.all %}
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{ link.nav_title }}<b class="caret"></b></a>
                            <ul class="dropdown-menu">
                        {% for n in link.nav_set.all %}
                                <li><a href="{{ n.nav_url }}">{{ n.nav_title }}</a></li>
                        {% endfor %}
                            
                            </ul>
                        </li>
                    {% else %}
                        {% if link.nav_dropdown == None %}
                        
                        <li><a href="{{ link.nav_url }}">{{ link.nav_title }}</a></li>
                         {% endif %}
                    {% endif %}
      
                {% endfor %}

            {% else %}

            {% endif %}
               
            </ul>
          </div><!--/.nav-collapse -->
            

              
            
        </div>
      </div>
      <!-- Begin page content -->
        <div class="container">
            <div class="page-header">
                <h1>{% block ptitle %} Development Page {% endblock %}</h1>
            </div>
        
        
            <div class="container">
                {% block content %} Development Page {% endblock %}
            </div>
        
        </div>
    </div>

 
 
 
     <div id="footer">
      <div class="container">
        <p class="text-muted">{% block sticky %} Development Page {% endblock %}</p>
      </div>
    </div>
 
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://code.jquery.com/jquery.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static "blog/dist/js/bootstrap.js" %}"></script>
  </body>
</html>

blog/templates/blog/index.html
N{% extends "blog/head.html" %}
{% block ptitle %}Blog Entries{% endblock %}

{% block content %}
{% if posts %}

    {% for post in pages %}
    

        <b></b><a href="{% url 'blog:detail' post.id %}">{{ post.post_title }}</a></b><br>
        Written By: {{ post.post_author }} <br><br>
        <div>{{ post.post_body }}</div> <br><br><br>
    {% endfor %}
    </ul>
{% else %}
    <p>No posts are available.</p>
{% endif %}
{% endblock %}

{% block sticky %}

    <span class="step-links">
        {% if pages.has_previous %}
            <a href="?page={{ pages.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ pages.number }} of {{ pages.paginator.num_pages }}.
        </span>

        {% if pages.has_next %}
            <a href="?page={{ pages.next_page_number }}">next</a>
        {% endif %}
    </span>


{% endblock %}

blog/templates/blog/post.html
{% extends "blog/head.html" %}
{% block ptitle %}<h1>{{ post.post_title }}</h1>{% endblock %}

<ul>


{% block content %}
{{ post.post_body}}
</ul>


{% csrf_token %}
    <div id="disqus_thread"></div>
    <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'luzdev'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
    <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
{% endblock %}   